from locust import HttpUser, task, between
import random


class WebsiteUser(HttpUser):
    wait_time = between(1, 5)  # uživatel čeká 1–5s mezi requesty

    @task
    def browse_site(self):
        endpoints = [
            "/",
            # "/anglictina",
            # "/anglictina/remove_student",
            # "/teacher/student_stats/1",
            # "/my_stats",
            # "/settings",
            # "/set_english_level",
            # "/set_theme",
            # "/upload_profile_pic",
            # "/request_teacher",
            # "/add_school",
            # "/teacher/create_group",
            # "/teacher/groups",
            # "/teacher/set_group",
            # "/add_student",
            # "/register",
            # "/login",
            # "/logout",
            # "/forgot_password",
            # "/verify_code",
            # "/terms",
            # "/cookies",
            # "/resend_code",
            # "/reset_password",
            # "/teacher/create_assignment",
            # "/student/group_assignments",
            # "/teacher/group_assignments",
            # "/teacher/delete_assignment/1",
            # "/teacher/edit_assignment/1",
            # "/anglictina/test",
            # "/song-selection",
            # "/exercise/1",
            # "/check-answer",
            # "/get_feedbacks",
            # "/feedback/1",
            # "/feedback",
            # "/feedback-post",
            # "/toggle_theme",
            # "/hangman",
            # "/hangman/start",
            # "/hangman/reset",
            # "/hangman/guess",
            # "/news",
            # "/get_news",
            # "/add_news",
            # "/gramatika",
            # "/sl_chat",
            # "/chat",
            # "/chat/start",
            # "/chat/next",
            # "/chat/test",
            # "/at-on",
            # "/at-on/create-sentence",
            # "/at-on/fill-word",
            # "/reset-progress",
            # "/api/top-users",
            # "/api/user/xp",
            # "/api/user/achievements",
            # "/api/achievements",
            # "/listening/A1/1",
            # "/validate_quiz",
            # "/add-review",
            # "/obchod",
            # "/buy_item",
            # "/zpravy",
            # "/zpravy/seznam",
            # "/zpravy/poslat",
            # "/roleplaying",
            # "/roleplaying/next",
            # "/ai/chats",
            # "/ai/chat/1",
            # "/ai",
            # "/dnd",
            # "/pexeso/rooms",
            # "/pexeso",
            # "/words.json",
            # "/pexeso/create_room",
            # "/kresleni",
            # "/psani/verejne",
            # "/psani",
            # "/psani/delete/1",
            # "/psani/edit/1",
            # "/admin/teacher_requests",
            # "/admin/teacher_requests/approve/1",
            # "/admin/teacher_requests/reject/1",
            # "/vlastni_music/check-answer",
            # "/vlastni_music",
            # "/proc_jit_s_nama"
        ]

        chosen = random.choice(endpoints)
        self.client.get(chosen)
# Spusť Locust pomocí příkazu: locust -f zatez.py
